language: javascript
script:
    - node tests.js
notifications:
    email:
        - sir@cmpwn.com
    irc:
        channels:
            - "chat.freenode.net#knightos"
        on_success: change
        on_failure: always
        skip_join: true
